import type { CharacterDef } from "../combat/types";
import { HitLevel } from "../combat/types";
import type { LabPreferences } from "./preferences";

interface LabViewOptions {
  character: CharacterDef;
  preferences: LabPreferences;
  dummyOptions: readonly [number, string][];
  hitboxesEnabled?: boolean;
  slowMotionEnabled?: boolean;
}

const KIT_INPUTS = ["↑ / Y", "← / X", "→ / B", "↓ / A"] as const;

export function buildLabView({ character, preferences, dummyOptions, hitboxesEnabled = false, slowMotionEnabled = false }: LabViewOptions): string {
  const hud = fighterHudMarkup(character.health, character.stamina);
  return `<a class="skip-link" href="#game-content">Skip to game content</a>
  <main class="lab-shell public-play" id="game-content">
    <header class="lab-header debugger-header"><div class="brand"><p class="eyebrow">HEXFRAME / TRAINING</p><h1>Hit. Pause. Practice.</h1><p>Practice live. Use Slow-mo and Hitboxes when you want a closer look.</p></div><div class="header-actions"><span class="controller-state" id="controller-state">Keyboard ready</span><button type="button" data-action="menu" aria-haspopup="dialog">Menu</button></div></header>

    <aside class="tutorial-prompt" id="tutorial-prompt" aria-labelledby="tutorial-prompt-title" hidden><div><strong id="tutorial-prompt-title">New to Training?</strong><span>Run the four-lesson tutorial without leaving the arena.</span></div><div><button class="primary" type="button" data-action="start-tutorial-prompt">Start tutorial</button><button type="button" data-action="dismiss-tutorial-prompt">Not now</button></div></aside>

    <section class="training-bar" aria-label="Training controls">
      <button class="primary" id="pause-control" type="button" data-action="pause" data-gamepad-nav>Pause</button>
      <button type="button" data-action="reset" data-gamepad-nav>Reset</button>
      <label data-gamepad-nav tabindex="0"><span>Dummy</span><select data-control="dummy" aria-label="Training dummy">${dummyOptions.map(([value, label]) => option(value, label)).join("")}</select></label>
      <button class="training-toggle" type="button" data-action="slow-mo" data-gamepad-nav aria-pressed="${slowMotionEnabled}">Slow-mo (25%)</button>
      <button class="training-toggle" type="button" data-action="hitboxes" data-gamepad-nav aria-pressed="${hitboxesEnabled}">Hitboxes (&#96;)</button>
    </section>

    <aside class="tutorial-hud" id="tutorial-hud" aria-live="polite" hidden><header><span id="tutorial-lesson-count">LESSON 1 / 4</span><strong id="tutorial-title">Movement</strong></header><div class="tutorial-objective"><small>OBJECTIVE</small><b id="tutorial-objective">Move forward</b><em id="tutorial-success"></em></div><p id="tutorial-hint"></p><strong class="tutorial-telegraph" id="tutorial-telegraph" hidden></strong><footer><button class="primary" type="button" data-action="next-tutorial-lesson" hidden>Next lesson</button><button type="button" data-action="exit-tutorial">Exit tutorial</button></footer></aside>

    <section class="debugger-workspace"><section class="playfield-card" aria-label="Combat arena"><div class="hud" aria-label="Fighter health and stamina">${hud}</div><div id="stage" class="stage"></div><div class="paused-overlay" id="paused-overlay" role="status" hidden><strong>PAUSED</strong><span>Press Start or Space to resume</span></div><div class="current-route"><span>ACTIVE</span><strong id="active-move">Ready</strong><em id="active-tags">Move, strike, and practice the route</em></div><div class="audio-caption" id="audio-caption" role="status" aria-live="polite" hidden></div><div class="sr-only" id="combat-announcer" role="status" aria-live="polite"></div></section></section>

    <footer class="control-legend"><span><b>MOVE</b> WASD / left stick</span><span><b>↑ / Y</b> Jab</span><span><b>← / X</b> Sweep</span><span><b>→ / B</b> Overhead</span><span><b>↓ / A</b> Uppercut</span><span><b>HITBOXES</b> \`</span><span><b>MENU</b> Esc / View</span></footer>

    <div class="menu-scrim" id="menu-scrim" hidden><aside class="lab-menu" id="lab-menu" role="dialog" aria-modal="true" aria-labelledby="menu-title" tabindex="-1"><header class="menu-header"><div><p class="eyebrow">HEXFRAME / TRAINING</p><h2 id="menu-title">Pause menu</h2></div></header><nav class="pause-menu-list" aria-label="Pause menu"><button class="primary" type="button" data-action="close-menu" data-gamepad-nav>Resume</button><button type="button" data-action="reset" data-gamepad-nav>Restart</button><button type="button" data-action="start-tutorial" data-gamepad-nav>Start tutorial</button><button type="button" data-menu-detail-target="moves" data-gamepad-nav>Move list</button><button type="button" data-menu-detail-target="settings" data-gamepad-nav>Settings</button><button type="button" data-menu-detail-target="controls" data-gamepad-nav>Controls</button><button type="button" data-action="return-main" data-gamepad-nav>Exit</button></nav><section class="menu-detail" id="menu-detail" aria-live="polite"><section data-menu-detail="moves" hidden><div class="settings-heading"><h2>Move list</h2><span>The fixed four-button kit and its authored frame data.</span></div>${moveListMarkup(character)}</section><section data-menu-detail="settings" hidden><div class="settings-heading"><h2>Settings</h2><span>One page of settings with behavior in the current Training MVP.</span></div>${settingsMarkup(preferences)}</section><section data-menu-detail="controls" hidden><div class="settings-heading"><h2>Controls</h2></div>${controlsMarkup()}</section></section><footer class="menu-footer"><span>Keyboard: Tab / arrows · Gamepad: D-pad + A · B/View closes</span><strong>Training controls remain available outside the pause menu</strong></footer></aside></div>
  </main>`;
}

function fighterHudMarkup(health: number, stamina: number): string { return `<div class="hud-side hud-side-party"><div class="hud-player hud-party-member"><span>YOU</span><div class="hud-meter-stack"><div class="health-track"><i id="health-p1"></i></div><div class="stamina-track"><i id="stamina-p1"></i></div></div><strong><b id="health-text-p1">${health}</b><small id="stamina-text-p1">${stamina} STA</small></strong></div></div><div class="hud-player hud-player-right"><strong><b id="health-text-p2">${health}</b><small id="stamina-text-p2">${stamina} STA</small></strong><div class="hud-meter-stack"><div class="health-track"><i id="health-p2"></i></div><div class="stamina-track"><i id="stamina-p2"></i></div></div><span>DUMMY</span></div>`; }

function moveListMarkup(character: CharacterDef): string {
  const rows = character.commands.map((command, index) => { const move = character.moves.find((candidate) => candidate.id === command.moveId); if (!move) return ""; const hitbox = move.hitboxes[0]; return `<tr data-move-id="${move.id}"><th scope="row"><strong>${KIT_INPUTS[index] ?? "—"}</strong><span>${titleCase(move.key)}</span></th><td>${hitbox ? hitLevelLabel(hitbox.level) : "—"}</td><td>${hitbox?.damage ?? 0}</td><td>${move.startup}</td><td>${move.active}</td><td>${move.recovery}</td></tr>`; }).join("");
  return `<div class="move-list-wrap"><table class="move-list"><thead><tr><th>Move</th><th>Level</th><th>Damage</th><th>Startup</th><th>Active</th><th>Recovery</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}
function hitLevelLabel(level: number): string { if (level === HitLevel.Overhead) return "Overhead"; if (level === HitLevel.Low) return "Low"; return "Mid"; }
function titleCase(value: string): string { return value.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }

function settingsMarkup(preferences: LabPreferences): string {
  const a = preferences.audio; const v = preferences.video; const x = preferences.accessibility; const c = preferences.controls;
  return `<div class="settings-content"><section class="settings-section"><h3>Audio</h3><div class="settings-fields">${rangeMarkup("Master volume", "audio", "master", a.master, 0, 1, .05)}${rangeMarkup("Combat effects", "audio", "sfx", a.sfx, 0, 1, .05)}${rangeMarkup("Interface", "audio", "ui", a.ui, 0, 1, .05)}${toggleMarkup("Audio captions", a.captions, pref("audio", "captions"))}${toggleMarkup("Mute when unfocused", a.muteUnfocused, pref("audio", "muteUnfocused"))}</div></section><section class="settings-section"><h3>Visual</h3><div class="settings-fields">${selectMarkup("Particles", "video", "particles", v.particles, [["off", "Off"], ["reduced", "Reduced"], ["full", "Full"]])}${rangeMarkup("Camera shake", "video", "cameraShake", v.cameraShake, 0, 1, .05)}${selectMarkup("Combat flashes", "video", "combatFlashes", v.combatFlashes, [["off", "Off"], ["reduced", "Reduced"], ["full", "Full"]])}${toggleMarkup("Damage numbers", v.damageNumbers, pref("video", "damageNumbers"))}${rangeMarkup("HUD opacity", "video", "hudOpacity", v.hudOpacity, .45, 1, .05)}</div></section><section class="settings-section"><h3>Accessibility</h3><div class="settings-fields">${selectMarkup("Theme", "accessibility", "theme", x.theme, [["system", "System"], ["dark", "Dark"], ["light", "Light"]])}${selectMarkup("Contrast", "accessibility", "contrast", x.contrast, [["normal", "Normal"], ["high", "High"]])}${selectMarkup("Motion", "accessibility", "motion", x.motion, [["system", "System"], ["full", "Full"], ["reduced", "Reduced"]])}${rangeMarkup("Text size", "accessibility", "textScale", x.textScale, .9, 1.6, .1)}${selectMarkup("Color vision", "accessibility", "colorVision", x.colorVision, [["default", "Default"], ["deuteranopia", "Deuteranopia"], ["protanopia", "Protanopia"], ["tritanopia", "Tritanopia"], ["monochrome", "Monochrome"]])}${toggleMarkup("Dyslexia-friendly type", x.dyslexiaFont, pref("accessibility", "dyslexiaFont"))}${toggleMarkup("Strong focus indicator", x.strongFocus, pref("accessibility", "strongFocus"))}${toggleMarkup("Screen reader combat log", x.screenReaderCombat, pref("accessibility", "screenReaderCombat"))}</div></section><section class="settings-section"><h3>Input</h3><div class="settings-fields">${selectMarkup("Input glyphs", "controls", "glyphs", c.glyphs, [["auto", "Automatic"], ["keyboard", "Keyboard"], ["xbox", "Gamepad"]])}${rangeMarkup("Stick deadzone", "controls", "stickDeadzone", c.stickDeadzone, .15, .9, .05)}${rangeMarkup("Vibration", "controls", "vibration", c.vibration, 0, 1, .05)}<button type="button" data-action="reset-preferences" data-gamepad-nav>Reset all settings</button></div></section></div>`;
}
function controlsMarkup(): string { return `<dl class="controls-list"><div><dt>Move</dt><dd>WASD / left stick</dd></div><div><dt>Jab</dt><dd>↑ / Y</dd></div><div><dt>Sweep</dt><dd>← / X</dd></div><div><dt>Overhead</dt><dd>→ / B</dd></div><div><dt>Uppercut</dt><dd>↓ / A</dd></div><div><dt>Play / pause</dt><dd>Space or P / Start</dd></div><div><dt>Hitboxes</dt><dd>\` or Training bar</dd></div><div><dt>Slow-mo</dt><dd>Training bar · 25%</dd></div><div><dt>Pause menu</dt><dd>Esc / View</dd></div><div><dt>Navigate Training controls</dt><dd>Pause, then D-pad + A</dd></div></dl>`; }
function rangeMarkup(label: string, section: string, key: string, value: number, min: number, max: number, step: number): string { const percent = Math.round(value * 100); return `<label class="setting-row setting-range" data-gamepad-nav tabindex="0"><strong>${label}</strong><span class="range-control"><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" ${pref(section, key)} data-pref-number aria-label="${label}" aria-valuetext="${percent}%"><output data-pref-output="${section}.${key}">${percent}%</output></span></label>`; }
function toggleMarkup(label: string, checked: boolean, attributes: string): string { return `<label class="setting-row setting-toggle" data-gamepad-nav tabindex="0"><strong>${label}</strong><input type="checkbox" ${checked ? "checked" : ""} ${attributes}><i aria-hidden="true"></i></label>`; }
function selectMarkup(label: string, section: string, key: string, value: string, options: readonly (readonly [string, string])[]): string { return `<label class="setting-row" data-gamepad-nav tabindex="0"><strong>${label}</strong><select ${pref(section, key)} aria-label="${label}">${options.map(([optionValue, optionLabel]) => `<option value="${optionValue}" ${optionValue === value ? "selected" : ""}>${optionLabel}</option>`).join("")}</select></label>`; }
function pref(section: string, key: string): string { return `data-pref-section="${section}" data-pref-key="${key}"`; }
function option(value: string | number, label: string): string { return `<option value="${value}">${label}</option>`; }
