import type { CharacterDef } from "../combat/types";
import { HitLevel } from "../combat/types";
import { moveTimelineMarkup } from "./inspector";
import type { LabPreferences } from "./preferences";

interface LabViewOptions {
  character: CharacterDef;
  preferences: LabPreferences;
  dummyOptions: readonly [number, string][];
  debugEnabled?: boolean;
}

const KIT_INPUTS = ["↑ / Y", "← / X", "→ / B", "↓ / A"] as const;

export function buildLabView({ character, preferences, dummyOptions, debugEnabled = false }: LabViewOptions): string {
  const initialMove = character.moves.find((move) => move.id === character.commands[0]?.moveId) ?? character.moves[0];
  const hud = fighterHudMarkup(character.health, character.stamina);
  const statusLanes = [0, 1].map((player) => `<div class="status-lane ${player === 0 ? "status-lane-you" : "status-lane-dummy"}" data-party-row="${player}" id="debuff-p${player + 1}" aria-label="Fighter ${player + 1} active debuffs"></div>`).join("");

  return `<a class="skip-link" href="#game-content">Skip to game content</a>
  <main class="lab-shell public-play" id="game-content">
    <header class="lab-header debugger-header"><div class="brand"><p class="eyebrow">HEXFRAME / TRAINING</p><h1>Hit. Pause. Inspect.</h1><p>Practice live. Turn on Debug when you want the exact frame.</p></div><div class="header-actions"><span class="controller-state" id="controller-state">Keyboard ready</span><button type="button" data-action="menu" aria-haspopup="dialog">Menu</button></div></header>

    <aside class="tutorial-prompt" id="tutorial-prompt" aria-labelledby="tutorial-prompt-title" hidden><div><strong id="tutorial-prompt-title">New to Training?</strong><span>Run the five-lesson tutorial without leaving the arena.</span></div><div><button class="primary" type="button" data-action="start-tutorial-prompt">Start tutorial</button><button type="button" data-action="dismiss-tutorial-prompt">Not now</button></div></aside>

    <section class="training-bar" aria-label="Training controls">
      <button class="primary" id="pause-control" type="button" data-action="pause" data-gamepad-nav>Pause</button>
      <button type="button" data-action="reset" data-gamepad-nav>Reset</button>
      <label data-gamepad-nav tabindex="0"><span>Dummy</span><select data-control="dummy" aria-label="Training dummy">${dummyOptions.map(([value, label]) => option(value, label)).join("")}</select></label>
      <label data-gamepad-nav tabindex="0"><span>Speed</span><select data-control="speed" aria-label="Simulation speed"><option value="25">25%</option><option value="50">50%</option><option value="100" selected>100%</option><option value="200">200%</option></select></label>
      <button class="debug-toggle" id="debug-control" type="button" data-action="debug" data-gamepad-nav aria-controls="debug-tools" aria-expanded="${debugEnabled}" aria-pressed="${debugEnabled}">Debug: ${debugEnabled ? "On" : "Off"} (\`)</button>
    </section>

    <aside class="tutorial-hud" id="tutorial-hud" aria-live="polite" hidden><header><span id="tutorial-lesson-count">LESSON 1 / 5</span><strong id="tutorial-title">Movement</strong></header><div class="tutorial-objective"><small>OBJECTIVE</small><b id="tutorial-objective">Move forward</b><em id="tutorial-success"></em></div><p id="tutorial-hint"></p><strong class="tutorial-telegraph" id="tutorial-telegraph" hidden></strong><footer><button class="primary" type="button" data-action="next-tutorial-lesson" hidden>Next lesson</button><button type="button" data-action="exit-tutorial">Exit tutorial</button></footer></aside>

    <section class="debugger-workspace"><section class="playfield-card" aria-label="Combat arena"><div class="hud" aria-label="Fighter health and stamina">${hud}</div>${statusLanes}<div id="stage" class="stage"></div><div class="paused-overlay" id="paused-overlay" role="status" hidden><strong>PAUSED</strong><span>Press Start or Space to resume</span></div><div class="current-route"><span>ACTIVE</span><strong id="active-move">Ready</strong><em id="active-tags">Move, strike, and inspect the result</em></div><div class="audio-caption" id="audio-caption" role="status" aria-live="polite" hidden></div><div class="sr-only" id="combat-announcer" role="status" aria-live="polite"></div></section></section>

    <section class="debug-tools" id="debug-tools" aria-label="Debug tools" ${debugEnabled ? "" : "hidden"}>
      <section class="frame-console" aria-label="Frame transport controls"><div class="global-frame"><span>FRAME</span><strong id="frame-readout">000000</strong><em id="play-state">LIVE</em></div><div class="frame-transport"><button type="button" data-action="back-10" data-gamepad-nav aria-label="Move backward ten frames">◀ −10</button><button type="button" data-action="back" data-gamepad-nav aria-label="Move backward one frame">◀ −1</button><button type="button" data-action="forward" data-gamepad-nav aria-label="Move forward one frame">+1 ▶</button><button type="button" data-action="forward-10" data-gamepad-nav aria-label="Move forward ten frames">+10 ▶</button></div><div class="frame-options"><label data-gamepad-nav tabindex="0"><input type="checkbox" data-control="pause-on-contact"> Pause on contact</label><span><kbd>Space</kbd> play/pause · <kbd>,</kbd> −1 · <kbd>.</kbd> +1</span><output id="timeline-status">Frame 0 · live</output></div></section>
      <section class="geometry-controls" aria-label="Combat geometry visibility"><strong>GEOMETRY</strong>${[["hitboxes", "Hitboxes"], ["hurtboxes", "Hurtboxes"], ["pushboxes", "Pushboxes"], ["origins", "Origins"], ["skeleton", "Skeleton"]].map(([key, label]) => `<label data-gamepad-nav tabindex="0"><input type="checkbox" data-debug="${key}"> ${label}</label>`).join("")}</section>
      <section class="debug-inspection-grid"><section class="frame-inspector" id="frame-inspector" aria-label="Authoritative frame inspector"></section><section class="move-timeline-console" id="move-timeline-console" aria-label="Move frame timeline">${moveTimelineMarkup(initialMove)}</section></section>
      <section class="debugger-lower-grid"><section class="interaction-console" aria-labelledby="interaction-title"><header><p>CONTACT HISTORY</p><h2 id="interaction-title">Interaction inspector</h2></header><div class="interaction-workspace" id="interaction-history"><p class="interaction-empty">No attack volume has touched a hurtbox in this run.</p></div></section></section>
      <section class="save-states" aria-label="Save states"><h3>Save states</h3>${[1, 2, 3].map((slot) => `<div><span>Slot ${slot}</span><button type="button" data-save="${slot}" data-gamepad-nav>Save</button><button type="button" data-load="${slot}" data-gamepad-nav disabled>Load</button></div>`).join("")}</section>
    </section>

    <footer class="control-legend"><span><b>MOVE</b> WASD / left stick</span><span><b>↑ / Y</b> Ember Palm</span><span><b>← / X</b> Ashen Sweep</span><span><b>→ / B</b> Frost Heel</span><span><b>↓ / A</b> Phoenix Drive</span><span><b>DEBUG</b> \`</span><span><b>MENU</b> Esc / View</span></footer>

    <div class="menu-scrim" id="menu-scrim" hidden><aside class="lab-menu" id="lab-menu" role="dialog" aria-modal="true" aria-labelledby="menu-title" tabindex="-1"><header class="menu-header"><div><p class="eyebrow">HEXFRAME / TRAINING</p><h2 id="menu-title">Pause menu</h2></div></header><nav class="pause-menu-list" aria-label="Pause menu"><button class="primary" type="button" data-action="close-menu" data-gamepad-nav>Resume</button><button type="button" data-action="reset" data-gamepad-nav>Restart</button><button type="button" data-action="start-tutorial" data-gamepad-nav>Start tutorial</button><button type="button" data-menu-detail-target="moves" data-gamepad-nav>Move list</button><button type="button" data-menu-detail-target="settings" data-gamepad-nav>Settings</button><button type="button" data-menu-detail-target="controls" data-gamepad-nav>Controls</button><button type="button" data-action="return-main" data-gamepad-nav>Exit</button></nav><section class="menu-detail" id="menu-detail" aria-live="polite"><section data-menu-detail="moves" hidden><div class="settings-heading"><h2>Move list</h2><span>The fixed four-button kit and its authored frame data.</span></div>${moveListMarkup(character)}</section><section data-menu-detail="settings" hidden><div class="settings-heading"><h2>Settings</h2><span>One page of settings with behavior in the current Training MVP.</span></div>${settingsMarkup(preferences)}</section><section data-menu-detail="controls" hidden><div class="settings-heading"><h2>Controls</h2></div>${controlsMarkup()}</section></section><footer class="menu-footer"><span>Keyboard: Tab / arrows · Gamepad: D-pad + A · B/View closes</span><strong>Debug remains available outside the pause menu</strong></footer></aside></div>
  </main>`;
}

function fighterHudMarkup(health: number, stamina: number): string { return `<div class="hud-side hud-side-party"><div class="hud-player hud-party-member"><span>YOU</span><div class="hud-meter-stack"><div class="health-track"><i id="health-p1"></i></div><div class="stamina-track"><i id="stamina-p1"></i></div></div><strong><b id="health-text-p1">${health}</b><small id="stamina-text-p1">${stamina} STA</small></strong></div></div><div class="hud-player hud-player-right"><strong><b id="health-text-p2">${health}</b><small id="stamina-text-p2">${stamina} STA</small></strong><div class="hud-meter-stack"><div class="health-track"><i id="health-p2"></i></div><div class="stamina-track"><i id="stamina-p2"></i></div></div><span>DUMMY</span></div>`; }

function moveListMarkup(character: CharacterDef): string {
  const rows = character.commands.map((command, index) => { const move = character.moves.find((candidate) => candidate.id === command.moveId); if (!move) return ""; const hitbox = move.hitboxes[0]; return `<tr data-move-id="${move.id}"><th scope="row"><strong>${KIT_INPUTS[index] ?? "—"}</strong><span>${titleCase(move.key)}</span></th><td>${hitbox ? hitLevelLabel(hitbox.level) : "—"}</td><td>${hitbox?.damage ?? 0}</td><td>${move.startup}</td><td>${move.active}</td><td>${move.recovery}</td></tr>`; }).join("");
  return `<div class="move-list-wrap"><table class="move-list"><thead><tr><th>Move</th><th>Level</th><th>Damage</th><th>Startup</th><th>Active</th><th>Recovery</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}
function hitLevelLabel(level: number): string { if (level === HitLevel.Overhead) return "Overhead"; if (level === HitLevel.Low) return "Low"; return "Mid"; }
function titleCase(value: string): string { return value.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }

function settingsMarkup(preferences: LabPreferences): string {
  const a = preferences.audio; const v = preferences.video; const x = preferences.accessibility; const c = preferences.controls;
  return `<div class="settings-content"><section class="settings-section"><h3>Audio</h3><div class="settings-fields">${rangeMarkup("Master volume", "audio", "master", a.master, 0, 1, .05)}${rangeMarkup("Combat effects", "audio", "sfx", a.sfx, 0, 1, .05)}${rangeMarkup("Interface", "audio", "ui", a.ui, 0, 1, .05)}${toggleMarkup("Audio captions", a.captions, pref("audio", "captions"))}${toggleMarkup("Mute when unfocused", a.muteUnfocused, pref("audio", "muteUnfocused"))}</div></section><section class="settings-section"><h3>Visual</h3><div class="settings-fields">${selectMarkup("Particles", "video", "particles", v.particles, [["off", "Off"], ["reduced", "Reduced"], ["full", "Full"]])}${rangeMarkup("Camera shake", "video", "cameraShake", v.cameraShake, 0, 1, .05)}${selectMarkup("Combat flashes", "video", "combatFlashes", v.combatFlashes, [["off", "Off"], ["reduced", "Reduced"], ["full", "Full"]])}${toggleMarkup("Damage numbers", v.damageNumbers, pref("video", "damageNumbers"))}${rangeMarkup("HUD opacity", "video", "hudOpacity", v.hudOpacity, .45, 1, .05)}</div></section><section class="settings-section"><h3>Accessibility</h3><div class="settings-fields">${selectMarkup("Theme", "accessibility", "theme", x.theme, [["system", "System"], ["dark", "Dark"], ["light", "Light"]])}${selectMarkup("Contrast", "accessibility", "contrast", x.contrast, [["normal", "Normal"], ["high", "High"]])}${selectMarkup("Motion", "accessibility", "motion", x.motion, [["system", "System"], ["full", "Full"], ["reduced", "Reduced"]])}${rangeMarkup("Text size", "accessibility", "textScale", x.textScale, .9, 1.6, .1)}${selectMarkup("Color vision", "accessibility", "colorVision", x.colorVision, [["default", "Default"], ["deuteranopia", "Deuteranopia"], ["protanopia", "Protanopia"], ["tritanopia", "Tritanopia"], ["monochrome", "Monochrome"]])}${toggleMarkup("Status patterns", x.statusPatterns, pref("accessibility", "statusPatterns"))}${toggleMarkup("Dyslexia-friendly type", x.dyslexiaFont, pref("accessibility", "dyslexiaFont"))}${toggleMarkup("Strong focus indicator", x.strongFocus, pref("accessibility", "strongFocus"))}${toggleMarkup("Screen reader combat log", x.screenReaderCombat, pref("accessibility", "screenReaderCombat"))}</div></section><section class="settings-section"><h3>Input</h3><div class="settings-fields">${selectMarkup("Input glyphs", "controls", "glyphs", c.glyphs, [["auto", "Automatic"], ["keyboard", "Keyboard"], ["xbox", "Gamepad"]])}${rangeMarkup("Stick deadzone", "controls", "stickDeadzone", c.stickDeadzone, .15, .9, .05)}${rangeMarkup("Vibration", "controls", "vibration", c.vibration, 0, 1, .05)}<button type="button" data-action="reset-preferences" data-gamepad-nav>Reset all settings</button></div></section></div>`;
}
function controlsMarkup(): string { return `<dl class="controls-list"><div><dt>Move</dt><dd>WASD / left stick</dd></div><div><dt>Ember Palm</dt><dd>↑ / Y</dd></div><div><dt>Ashen Sweep</dt><dd>← / X</dd></div><div><dt>Frost Heel</dt><dd>→ / B</dd></div><div><dt>Phoenix Drive</dt><dd>↓ / A</dd></div><div><dt>Play / pause</dt><dd>Space or P / Start</dd></div><div><dt>Debug</dt><dd>\`</dd></div><div><dt>Step</dt><dd>, and . / bumpers while paused</dd></div><div><dt>Pause menu</dt><dd>Esc / View</dd></div><div><dt>Navigate Training controls</dt><dd>Pause, then D-pad + A</dd></div></dl>`; }
function rangeMarkup(label: string, section: string, key: string, value: number, min: number, max: number, step: number): string { const percent = Math.round(value * 100); return `<label class="setting-row setting-range" data-gamepad-nav tabindex="0"><strong>${label}</strong><span class="range-control"><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" ${pref(section, key)} data-pref-number aria-label="${label}" aria-valuetext="${percent}%"><output data-pref-output="${section}.${key}">${percent}%</output></span></label>`; }
function toggleMarkup(label: string, checked: boolean, attributes: string): string { return `<label class="setting-row setting-toggle" data-gamepad-nav tabindex="0"><strong>${label}</strong><input type="checkbox" ${checked ? "checked" : ""} ${attributes}><i aria-hidden="true"></i></label>`; }
function selectMarkup(label: string, section: string, key: string, value: string, options: readonly (readonly [string, string])[]): string { return `<label class="setting-row" data-gamepad-nav tabindex="0"><strong>${label}</strong><select ${pref(section, key)} aria-label="${label}">${options.map(([optionValue, optionLabel]) => `<option value="${optionValue}" ${optionValue === value ? "selected" : ""}>${optionLabel}</option>`).join("")}</select></label>`; }
function pref(section: string, key: string): string { return `data-pref-section="${section}" data-pref-key="${key}"`; }
function option(value: string | number, label: string): string { return `<option value="${value}">${label}</option>`; }
